# docker-compose版本
version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: .
        # 指定使用的Dockerfile
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql/mysql-server:5.7.28
    restart: always
    environment:
      MYSQL_DATABASE: book
      MYSQL_USER: root
      MYSQL_PASSWD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
     - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306